/*

Package dirserve implements more secure directory serving.

No web framework can ship without being able to simply serve files out of
directories, of course. But thar be dragons here, and numerous security
vulnerabilities can be traced back to poor implementations of directory
serving, including but not limited to:

 * permitting traversal via ..
 * happily revealing the existence of and serving hidden files
   or temporary files generated by emacs or something
 * MIME-type mismatches can occur in detection
 * XSS in the file display

(To be clear, the standard Go implementation should be immune to directory
traversal and XSS.)

This module implements paranoid file serving out of disk directories:

 * by default no traversal allowed, including no downward traversal
   unless explicitly permitted
 * a conservative policy on file names permitted, in particular
   intended to block temporary files generated by editors
 * No MIME-type guessing unless you ask for it
 * defaults to indexing off
 * no UNIX "hidden" files
 * by default, serves only "normal" files. No symlinks, no devices,
   pipes, directories, executables, etc.
 * The X-Content-Type-Options header is set to nosniff.

A FileSystemServer is a REST server that implements the above.

Someday a streaming interface that integrates with fsnotify would be neat,
but this focuses on the static case for now.

Significant portions of this are pulled from net/http, but have to be
modified to implement the above.

Despite all this, IE 8 and older is fairly aggressive about content
sniffing, and it may be dangerous to permit any user-provided content in a
directory served via this module. It may be somewhat safer on modern
browsers, but it's hard to prove the long-standing minefields in the
area of "detecting something as HTML even if the Content-Type says
otherwise" are hard to prove fixed. Putting user content in a
FileSystemServer and trying to serve out content correctly is still
a minefield, and any additional validation you can add for your use case
is well advised.

FIXME: Provide a clean example of how to wrap this.

Improvements

 * Go has no generic "file is hidden" attribute; could use some OS-specific
   code. This is currently expected to be implemented by the ShowFile
   filters.

*/
package dirserve
